package mnb

// Generated by https://github.com/cloudescape/gowsdl
// Do not modify
// Copyright (c) 2014, Cloudescape. All rights reserved.
import (
	"encoding/xml"
	"time"

	gowsdl "github.com/cloudescape/gowsdl/generator"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type GetInfo struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetInfo"`
}

type GetInfoResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetInfoResponse"`

	GetInfoResult string `xml:"GetInfoResult,omitempty"`
}

type GetCurrentExchangeRates struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrentExchangeRates"`
}

type GetCurrentExchangeRatesResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrentExchangeRatesResponse"`

	GetCurrentExchangeRatesResult string `xml:"GetCurrentExchangeRatesResult,omitempty"`
}

type GetExchangeRates struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetExchangeRates"`

	StartDate     string `xml:"startDate,omitempty"`
	EndDate       string `xml:"endDate,omitempty"`
	CurrencyNames string `xml:"currencyNames,omitempty"`
}

type GetExchangeRatesResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetExchangeRatesResponse"`

	GetExchangeRatesResult string `xml:"GetExchangeRatesResult,omitempty"`
}

type GetDateInterval struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetDateInterval"`
}

type GetDateIntervalResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetDateIntervalResponse"`

	GetDateIntervalResult string `xml:"GetDateIntervalResult,omitempty"`
}

type GetCurrencies struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrencies"`
}

type GetCurrenciesResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrenciesResponse"`

	GetCurrenciesResult string `xml:"GetCurrenciesResult,omitempty"`
}

type GetCurrencyUnits struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrencyUnits"`

	CurrencyNames string `xml:"currencyNames,omitempty"`
}

type GetCurrencyUnitsResponse struct {
	XMLName xml.Name `xml:"http://www.mnb.hu/webservices/ GetCurrencyUnitsResponse"`

	GetCurrencyUnitsResult string `xml:"GetCurrencyUnitsResult,omitempty"`
}

type MNBArfolyamServiceSoap struct {
	client *gowsdl.SoapClient
}

func NewMNBArfolyamServiceSoap(url string, tls bool) *MNBArfolyamServiceSoap {
	if url == "" {
		url = "http://www.mnb.hu/arfolyamok.asmx"
	}
	client := gowsdl.NewSoapClient(url, tls)

	return &MNBArfolyamServiceSoap{
		client: client,
	}
}

func (service *MNBArfolyamServiceSoap) GetInfo(request *GetInfo) (*GetInfoResponse, error) {
	response := &GetInfoResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetInfo", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *MNBArfolyamServiceSoap) GetCurrentExchangeRates(request *GetCurrentExchangeRates) (*GetCurrentExchangeRatesResponse, error) {
	response := &GetCurrentExchangeRatesResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetCurrentExchangeRates", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *MNBArfolyamServiceSoap) GetExchangeRates(request *GetExchangeRates) (*GetExchangeRatesResponse, error) {
	response := &GetExchangeRatesResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetExchangeRates", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *MNBArfolyamServiceSoap) GetDateInterval(request *GetDateInterval) (*GetDateIntervalResponse, error) {
	response := &GetDateIntervalResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetDateInterval", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *MNBArfolyamServiceSoap) GetCurrencies(request *GetCurrencies) (*GetCurrenciesResponse, error) {
	response := &GetCurrenciesResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetCurrencies", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *MNBArfolyamServiceSoap) GetCurrencyUnits(request *GetCurrencyUnits) (*GetCurrencyUnitsResponse, error) {
	response := &GetCurrencyUnitsResponse{}
	err := service.client.Call("http://www.mnb.hu/webservices/GetCurrencyUnits", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}
