// Code generated by qtc from "mnb.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line mnb.qtpl:1
package mnb

//line mnb.qtpl:1
import "time"

//line mnb.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mnb.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mnb.qtpl:5
func streamprintDate(qw422016 *qt422016.Writer, t time.Time) {
//line mnb.qtpl:6
	if !t.IsZero() {
//line mnb.qtpl:6
		qw422016.N().S(t.Format("2006-01-02"))
//line mnb.qtpl:6
	}
//line mnb.qtpl:7
}

//line mnb.qtpl:7
func writeprintDate(qq422016 qtio422016.Writer, t time.Time) {
//line mnb.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:7
	streamprintDate(qw422016, t)
//line mnb.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:7
}

//line mnb.qtpl:7
func printDate(t time.Time) string {
//line mnb.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:7
	writeprintDate(qb422016, t)
//line mnb.qtpl:7
	qs422016 := string(qb422016.B)
//line mnb.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:7
	return qs422016
//line mnb.qtpl:7
}

//line mnb.qtpl:9
func (req MNB) StreamGetCentralBankBaseRateXML(qw422016 *qt422016.Writer, start, end time.Time) {
//line mnb.qtpl:9
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCentralBankBaseRate>`)
//line mnb.qtpl:14
	if !start.IsZero() {
//line mnb.qtpl:14
		qw422016.N().S(`<web:startDate>`)
//line mnb.qtpl:14
		streamprintDate(qw422016, start)
//line mnb.qtpl:14
		qw422016.N().S(`</web:startDate>`)
//line mnb.qtpl:14
	}
//line mnb.qtpl:15
	if !end.IsZero() {
//line mnb.qtpl:15
		qw422016.N().S(`<web:endDate>`)
//line mnb.qtpl:15
		streamprintDate(qw422016, end)
//line mnb.qtpl:15
		qw422016.N().S(`</web:endDate>`)
//line mnb.qtpl:15
	}
//line mnb.qtpl:15
	qw422016.N().S(`</web:GetCentralBankBaseRate></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:19
}

//line mnb.qtpl:19
func (req MNB) WriteGetCentralBankBaseRateXML(qq422016 qtio422016.Writer, start, end time.Time) {
//line mnb.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:19
	req.StreamGetCentralBankBaseRateXML(qw422016, start, end)
//line mnb.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:19
}

//line mnb.qtpl:19
func (req MNB) GetCentralBankBaseRateXML(start, end time.Time) string {
//line mnb.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:19
	req.WriteGetCentralBankBaseRateXML(qb422016, start, end)
//line mnb.qtpl:19
	qs422016 := string(qb422016.B)
//line mnb.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:19
	return qs422016
//line mnb.qtpl:19
}

//line mnb.qtpl:21
func (req MNB) StreamGetCurrencyUnitsXML(qw422016 *qt422016.Writer, currencies ...string) {
//line mnb.qtpl:21
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCurrencyUnits>`)
//line mnb.qtpl:26
	for _, curr := range currencies {
//line mnb.qtpl:26
		qw422016.N().S(`<web:currencyNames>`)
//line mnb.qtpl:26
		qw422016.N().S(curr)
//line mnb.qtpl:26
		qw422016.N().S(`</web:currencyNames>`)
//line mnb.qtpl:26
	}
//line mnb.qtpl:26
	qw422016.N().S(`</web:GetCurrencyUnits></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:30
}

//line mnb.qtpl:30
func (req MNB) WriteGetCurrencyUnitsXML(qq422016 qtio422016.Writer, currencies ...string) {
//line mnb.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:30
	req.StreamGetCurrencyUnitsXML(qw422016, currencies...)
//line mnb.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:30
}

//line mnb.qtpl:30
func (req MNB) GetCurrencyUnitsXML(currencies ...string) string {
//line mnb.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:30
	req.WriteGetCurrencyUnitsXML(qb422016, currencies...)
//line mnb.qtpl:30
	qs422016 := string(qb422016.B)
//line mnb.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:30
	return qs422016
//line mnb.qtpl:30
}

//line mnb.qtpl:32
func (req MNB) StreamGetExchangeRatesXML(qw422016 *qt422016.Writer, start, end time.Time, currencies ...string) {
//line mnb.qtpl:32
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetExchangeRates>`)
//line mnb.qtpl:37
	if !start.IsZero() {
//line mnb.qtpl:37
		qw422016.N().S(`<web:startDate>`)
//line mnb.qtpl:37
		streamprintDate(qw422016, start)
//line mnb.qtpl:37
		qw422016.N().S(`</web:startDate>`)
//line mnb.qtpl:37
	}
//line mnb.qtpl:38
	if !end.IsZero() {
//line mnb.qtpl:38
		qw422016.N().S(`<web:endDate>`)
//line mnb.qtpl:38
		streamprintDate(qw422016, end)
//line mnb.qtpl:38
		qw422016.N().S(`</web:endDate>`)
//line mnb.qtpl:38
	}
//line mnb.qtpl:38
	qw422016.N().S(`<web:currencyNames>`)
//line mnb.qtpl:39
	for i, curr := range currencies {
//line mnb.qtpl:39
		if i != 0 {
//line mnb.qtpl:39
			qw422016.N().S(`,`)
//line mnb.qtpl:39
		}
//line mnb.qtpl:39
		qw422016.N().S(curr)
//line mnb.qtpl:39
	}
//line mnb.qtpl:39
	qw422016.N().S(`</web:currencyNames></web:GetExchangeRates></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:43
}

//line mnb.qtpl:43
func (req MNB) WriteGetExchangeRatesXML(qq422016 qtio422016.Writer, start, end time.Time, currencies ...string) {
//line mnb.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:43
	req.StreamGetExchangeRatesXML(qw422016, start, end, currencies...)
//line mnb.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:43
}

//line mnb.qtpl:43
func (req MNB) GetExchangeRatesXML(start, end time.Time, currencies ...string) string {
//line mnb.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:43
	req.WriteGetExchangeRatesXML(qb422016, start, end, currencies...)
//line mnb.qtpl:43
	qs422016 := string(qb422016.B)
//line mnb.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:43
	return qs422016
//line mnb.qtpl:43
}
