// Code generated by qtc from "mnb.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line mnb.qtpl:1
package mnb

//line mnb.qtpl:1
import "time"

//line mnb.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mnb.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mnb.qtpl:5
func streamprintDate(qw422016 *qt422016.Writer, t time.Time) {
//line mnb.qtpl:6
	if !t.IsZero() {
//line mnb.qtpl:6
		qw422016.N().S(t.Format("2006-01-02"))
//line mnb.qtpl:6
	}
//line mnb.qtpl:7
}

//line mnb.qtpl:7
func writeprintDate(qq422016 qtio422016.Writer, t time.Time) {
//line mnb.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:7
	streamprintDate(qw422016, t)
//line mnb.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:7
}

//line mnb.qtpl:7
func printDate(t time.Time) string {
//line mnb.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:7
	writeprintDate(qb422016, t)
//line mnb.qtpl:7
	qs422016 := string(qb422016.B)
//line mnb.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:7
	return qs422016
//line mnb.qtpl:7
}

//line mnb.qtpl:9
func (req MNB) StreamGetCurrentCentralBankBaseRateXML(qw422016 *qt422016.Writer) {
//line mnb.qtpl:9
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCurrentCentralBankBaseRate/></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:16
}

//line mnb.qtpl:16
func (req MNB) WriteGetCurrentCentralBankBaseRateXML(qq422016 qtio422016.Writer) {
//line mnb.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:16
	req.StreamGetCurrentCentralBankBaseRateXML(qw422016)
//line mnb.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:16
}

//line mnb.qtpl:16
func (req MNB) GetCurrentCentralBankBaseRateXML() string {
//line mnb.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:16
	req.WriteGetCurrentCentralBankBaseRateXML(qb422016)
//line mnb.qtpl:16
	qs422016 := string(qb422016.B)
//line mnb.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:16
	return qs422016
//line mnb.qtpl:16
}

//line mnb.qtpl:18
func (req MNB) StreamGetCentralBankBaseRateXML(qw422016 *qt422016.Writer, start, end time.Time) {
//line mnb.qtpl:18
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCentralBankBaseRate>`)
//line mnb.qtpl:23
	if !start.IsZero() {
//line mnb.qtpl:23
		qw422016.N().S(`<web:startDate>`)
//line mnb.qtpl:23
		streamprintDate(qw422016, start)
//line mnb.qtpl:23
		qw422016.N().S(`</web:startDate>`)
//line mnb.qtpl:23
	}
//line mnb.qtpl:24
	if !end.IsZero() {
//line mnb.qtpl:24
		qw422016.N().S(`<web:endDate>`)
//line mnb.qtpl:24
		streamprintDate(qw422016, end)
//line mnb.qtpl:24
		qw422016.N().S(`</web:endDate>`)
//line mnb.qtpl:24
	}
//line mnb.qtpl:24
	qw422016.N().S(`</web:GetCentralBankBaseRate></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:28
}

//line mnb.qtpl:28
func (req MNB) WriteGetCentralBankBaseRateXML(qq422016 qtio422016.Writer, start, end time.Time) {
//line mnb.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:28
	req.StreamGetCentralBankBaseRateXML(qw422016, start, end)
//line mnb.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:28
}

//line mnb.qtpl:28
func (req MNB) GetCentralBankBaseRateXML(start, end time.Time) string {
//line mnb.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:28
	req.WriteGetCentralBankBaseRateXML(qb422016, start, end)
//line mnb.qtpl:28
	qs422016 := string(qb422016.B)
//line mnb.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:28
	return qs422016
//line mnb.qtpl:28
}

//line mnb.qtpl:30
func (req MNB) StreamGetCurrenciesXML(qw422016 *qt422016.Writer) {
//line mnb.qtpl:30
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCurrencies/></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:37
}

//line mnb.qtpl:37
func (req MNB) WriteGetCurrenciesXML(qq422016 qtio422016.Writer) {
//line mnb.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:37
	req.StreamGetCurrenciesXML(qw422016)
//line mnb.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:37
}

//line mnb.qtpl:37
func (req MNB) GetCurrenciesXML() string {
//line mnb.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:37
	req.WriteGetCurrenciesXML(qb422016)
//line mnb.qtpl:37
	qs422016 := string(qb422016.B)
//line mnb.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:37
	return qs422016
//line mnb.qtpl:37
}

//line mnb.qtpl:39
func (req MNB) StreamGetCurrencyUnitsXML(qw422016 *qt422016.Writer, currencies ...string) {
//line mnb.qtpl:39
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCurrencyUnits>`)
//line mnb.qtpl:44
	for _, curr := range currencies {
//line mnb.qtpl:44
		qw422016.N().S(`<web:currencyNames>`)
//line mnb.qtpl:44
		qw422016.N().S(curr)
//line mnb.qtpl:44
		qw422016.N().S(`</web:currencyNames>`)
//line mnb.qtpl:44
	}
//line mnb.qtpl:44
	qw422016.N().S(`</web:GetCurrencyUnits></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:48
}

//line mnb.qtpl:48
func (req MNB) WriteGetCurrencyUnitsXML(qq422016 qtio422016.Writer, currencies ...string) {
//line mnb.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:48
	req.StreamGetCurrencyUnitsXML(qw422016, currencies...)
//line mnb.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:48
}

//line mnb.qtpl:48
func (req MNB) GetCurrencyUnitsXML(currencies ...string) string {
//line mnb.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:48
	req.WriteGetCurrencyUnitsXML(qb422016, currencies...)
//line mnb.qtpl:48
	qs422016 := string(qb422016.B)
//line mnb.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:48
	return qs422016
//line mnb.qtpl:48
}

//line mnb.qtpl:50
func (req MNB) StreamGetCurrentExchangeRatesXML(qw422016 *qt422016.Writer) {
//line mnb.qtpl:50
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetCurrentExchangeRates/></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:57
}

//line mnb.qtpl:57
func (req MNB) WriteGetCurrentExchangeRatesXML(qq422016 qtio422016.Writer) {
//line mnb.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:57
	req.StreamGetCurrentExchangeRatesXML(qw422016)
//line mnb.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:57
}

//line mnb.qtpl:57
func (req MNB) GetCurrentExchangeRatesXML() string {
//line mnb.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:57
	req.WriteGetCurrentExchangeRatesXML(qb422016)
//line mnb.qtpl:57
	qs422016 := string(qb422016.B)
//line mnb.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:57
	return qs422016
//line mnb.qtpl:57
}

//line mnb.qtpl:59
func (req MNB) StreamGetDateIntervalXML(qw422016 *qt422016.Writer) {
//line mnb.qtpl:59
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetDateInterval/></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:66
}

//line mnb.qtpl:66
func (req MNB) WriteGetDateIntervalXML(qq422016 qtio422016.Writer) {
//line mnb.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:66
	req.StreamGetDateIntervalXML(qw422016)
//line mnb.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:66
}

//line mnb.qtpl:66
func (req MNB) GetDateIntervalXML() string {
//line mnb.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:66
	req.WriteGetDateIntervalXML(qb422016)
//line mnb.qtpl:66
	qs422016 := string(qb422016.B)
//line mnb.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:66
	return qs422016
//line mnb.qtpl:66
}

//line mnb.qtpl:68
func (req MNB) StreamGetInfoXML(qw422016 *qt422016.Writer) {
//line mnb.qtpl:68
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetInfo/></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:75
}

//line mnb.qtpl:75
func (req MNB) WriteGetInfoXML(qq422016 qtio422016.Writer) {
//line mnb.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:75
	req.StreamGetInfoXML(qw422016)
//line mnb.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:75
}

//line mnb.qtpl:75
func (req MNB) GetInfoXML() string {
//line mnb.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:75
	req.WriteGetInfoXML(qb422016)
//line mnb.qtpl:75
	qs422016 := string(qb422016.B)
//line mnb.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:75
	return qs422016
//line mnb.qtpl:75
}

//line mnb.qtpl:77
func (req MNB) StreamGetExchangeRatesXML(qw422016 *qt422016.Writer, start, end time.Time, currencies ...string) {
//line mnb.qtpl:77
	qw422016.N().S(`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.mnb.hu/webservices/"><soapenv:Header/><soapenv:Body><web:GetExchangeRates>`)
//line mnb.qtpl:82
	if !start.IsZero() {
//line mnb.qtpl:82
		qw422016.N().S(`<web:startDate>`)
//line mnb.qtpl:82
		streamprintDate(qw422016, start)
//line mnb.qtpl:82
		qw422016.N().S(`</web:startDate>`)
//line mnb.qtpl:82
	}
//line mnb.qtpl:83
	if !end.IsZero() {
//line mnb.qtpl:83
		qw422016.N().S(`<web:endDate>`)
//line mnb.qtpl:83
		streamprintDate(qw422016, end)
//line mnb.qtpl:83
		qw422016.N().S(`</web:endDate>`)
//line mnb.qtpl:83
	}
//line mnb.qtpl:84
	for _, curr := range currencies {
//line mnb.qtpl:84
		qw422016.N().S(`<web:currencyNames>`)
//line mnb.qtpl:84
		qw422016.N().S(curr)
//line mnb.qtpl:84
		qw422016.N().S(`</web:currencyNames>`)
//line mnb.qtpl:84
	}
//line mnb.qtpl:84
	qw422016.N().S(`</web:GetExchangeRates></soapenv:Body></soapenv:Envelope>`)
//line mnb.qtpl:88
}

//line mnb.qtpl:88
func (req MNB) WriteGetExchangeRatesXML(qq422016 qtio422016.Writer, start, end time.Time, currencies ...string) {
//line mnb.qtpl:88
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mnb.qtpl:88
	req.StreamGetExchangeRatesXML(qw422016, start, end, currencies...)
//line mnb.qtpl:88
	qt422016.ReleaseWriter(qw422016)
//line mnb.qtpl:88
}

//line mnb.qtpl:88
func (req MNB) GetExchangeRatesXML(start, end time.Time, currencies ...string) string {
//line mnb.qtpl:88
	qb422016 := qt422016.AcquireByteBuffer()
//line mnb.qtpl:88
	req.WriteGetExchangeRatesXML(qb422016, start, end, currencies...)
//line mnb.qtpl:88
	qs422016 := string(qb422016.B)
//line mnb.qtpl:88
	qt422016.ReleaseByteBuffer(qb422016)
//line mnb.qtpl:88
	return qs422016
//line mnb.qtpl:88
}
